baseURL = 'https://dil-o-dimagh.onrender.com/'
languageCode = 'en-us'
title = 'Dil-o-Dimagh'
theme = ["PaperMod"]

[params.homeInfoParams]
Title = "Hi, this is Mubashir!"
Content = "Currently under construction."

[[params.socialIcons]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/mubashir-zamir-96b9491b4"

[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/mubashirzamir"

[module]
  [[module.mounts]]
    source = '/home/mushi/personal/obsidian/fikr-nama/Dil-o-Dimagh'
    target = 'content'
