baseURL = 'https://dil-o-dimagh.onrender.com/'
languageCode = 'en-us'
title = 'Dil-o-Dimagh'
theme = ["PaperMod"]

[params.homeInfoParams]
Title = "Hi, this is Mubashir!"
Content = "I share things I find interesting on here."

[[params.socialIcons]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/mubashir-zamir-96b9491b4"

[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/mubashirzamir"

[params]
ShowReadingTime = true
ShowCodeCopyButtons = true
hideFooter = true

ShowToc = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[menu]
  [[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 1
    
[module]
  [[module.mounts]]
    source = '/home/mushi/personal/fikr-nama/Dil-o-Dimagh'
    target = 'content'
